apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: default
spec:
  encryptedData:
    GITHUB_PAT: AgAfFWJEI+tthl2IGjOnlWwWKOm306oy2xdkJhE4fluv3L6kiectxQvxRc03dcWM+JQXVEwQ3AOqiU8NPP5S5qNCk6jgpmfa0rIufeq1HjvcRufGWUvv/OZ4QkGdwXTcqYHDBmK66scRSvQn9kvDK79bzRQsb1Vm54SNQmELTuvqHyTiU0ZshOhZeUd9Y8sTm6dUelBlREdn/U+P0Zrl+FASUTBOkogB3rS7uDeIA0aFciOh2ipY0byt4wbIo8C7eq4/g1O8+CpzH7atMdL3xw3D7fHnvGj8anRy6sElXsUA8ZPL/B3rkjNclh2Rqkr7Sb65gerxEjVUO9LJWgev3ETYjxWJlqxX/EH+ahodmJDxlU8wcl6dbFMiLupAeJXvCFdhupabyaacdDRrTiIsoUHfOxT4eTJ0xVWdtSVC7PGb7n9bMtKcdB/QZHNiaFe56SZeRrbw5DWSq0fIsLu5mbVGpMDClsEnEHeNAERhJqOM4QGkTCkTVvmC7OwTbC0iCEwhZ/lSLbWi5IPS/cTlt+klxFYTWULPe1UR3F8pCfHdaxvL9TTlGGwv9SOhu6Rocr6tBEvtiOu+ZL9RJl/Sj0h2SICrIN2+n2IEnVbYiCSrAG9ZkENWMFP1jbxEbEpg8wE0I95jDlgE4TxTf9f7Yvs9ZVMtWvkI8IljazD2Uv5pajojmNbllyvrblkK/0iVmLKBfQPji2xeLYD3wZlktc3rZDEtCK82GquIK5ceEq5HsPl91l4b2OJT
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: 'true'
      creationTimestamp: null
      name: homepage-secret
      namespace: default
    type: Opaque
