apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: default
spec:
  encryptedData:
    GITHUB_PAT: AgAD3k7z3I3QimLVBujPitFm9bLzot6B8vCoYE1lxxjSMPFW/vVKl9IBan0FtIESAdwfAYbmYKCVHDPfjdp14D80vA0HiB/3Jo8dsw7now+48L25zX0UasVGnAN6Yh/UnUwa+zlOUA3iqW8BBYXOLIubF3R2uo5Wi6ActzconR1c3en/CGKgxGjlbc3Eeuq5+/MRa6dkFwOHGuENllZFQdTslazOHjqm8CoEoI3YL4SH8fwp/9ypRxvbDl5xNFGoCXwafVIIpmkHlAEUhYQUkKJjENAy2VGIbm0Wxs3ybBHLMtbCe+im0fYmSpv+X1Hd3AgoVav7CLZJOU2vNitx+W1MwoIaY5DyWfyt7rL2ZvgR+17fRNbDdXcXXQ8oBl6FAiALyWbhfR4ZxlsxfEg41rpTTj5EY77gBq7XEdVB4K2BvFn/zcd1I/iQLYBMlNTIscbsxKN5qAJcJSX4El5Nv4WnR6XFJy6htzPKZ8t4ep99Xi8A9164Ij1Q0E91vqX5lMzqOtF0xYQedx/qmLDPBBVhZ/NDtBLfo8aa8kJ37et7guJWqBb1TafBeB73a6s7Tc0o4vPwf/gXihU7gR2QpKzaHSRMwBCyT8ltS7NVAU6lyr4RLq5xnVq0UmyaSnKGPPxkrp+hJMCjUSxNp66ma0fP1CfvuT22DcKVKQGMs1T/1zkvcGAxfM8ptTqmnT7vI/ytnjyKSqM29Myxuabnb0KPrfmt+7dnSjIwM8icdoQ3D68u3zrCdKj7
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: 'true'
      creationTimestamp: null
      name: homepage-secret
      namespace: default
    type: Opaque
