name: Build and Publish

on: workflow_dispatch

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          export GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)"
          export VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')"
          export IMAGE=ghcr.io/${{ github.repository }}:$VERSION-${{ github.ref }}-$GITHUB_SHA_SHORT

          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          echo $GITHUB_ENV

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE }}
          file: ./Containerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
