name: Preliminary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  preliminary-checks:
    uses: LoLei/util/.github/workflows/yarn-preliminary.yml@main
    with:
      node-version: '12.18.3'
      format: true
      lint: true
      test: true
